name: memory_enhancer_app
description: A mobile application to assist users with short-term memory loss

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  avatar_glow: ^2.0.1
  highlight_text: ^1.0.0
  stacked: ^2.1.9
  get_it: ^7.1.3
  injectable: ^1.4.1
  auto_route: ^2.2.0
  injectable_generator: ^1.4.1
  _fe_analyzer_shared: ^22.0.0
  wakelock: ^0.5.2
  stacked_themes: ^0.3.5
  google_fonts: ^2.1.0
  auto_route_generator: ^2.1.0
  xml: ^5.1.2
  nanoid: ^1.0.0
  intl: ^0.17.0
  encrypt: ^5.0.0
  youtube_player_flutter: ^8.0.0
  url_launcher: ^6.0.9
  mockito: ^5.0.12
  flutter_sound: ^8.2.5
  permission_handler: ^8.1.4+2
  porcupine: ^1.9.13
  text_to_speech: ^0.2.3
  flutter_launcher_icons: ^0.9.1
  flutter_native_splash: ^1.2.0

dev_dependencies:
  build_runner: ^2.0.5
  flutter_test:
    sdk: flutter


# Configuration for application icon
flutter_icons:
  ios: true
  android: true
  image_path_ios: "images/app_icon.png"
  image_path_android: "images/app_icon.png"
  adaptive_icon_background: "#f70d33" # or image
  adaptive_icon_foreground: "images/app_icon_foreground.png"


# Configuration for splash screen
flutter_native_splash:
  image: images/logo.png
  color: "#f70d33"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  fonts:
    - family:  MyFlutterApp
      fonts:
        - asset: fonts/MyFlutterApp.ttf

  assets:
    - assets/text/notes.txt
    - assets/text/words.txt
    - assets/settings/default_start_record_triggers.txt
    - assets/settings/default_stop_record_triggers.txt
    - assets/settings/default_recall_triggers.txt
    - assets/settings/settingsValues.xml
    - assets/porcupine/hey_amazing_en_android.ppn
    - assets/porcupine/hey_amazing_en_ios.ppn
    - assets/ibm_watson/speech_to_text_credentials.xml
    - assets/how_to_videos/howToVideoLinks.xml

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
